plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    id 'com.google.gms.google-services' version '4.4.2' apply false
    id 'com.google.firebase.crashlytics'
    alias(libs.plugins.google.firebase.firebase.perf)


}

android {
    namespace 'android.iocl.dac_collector'
    compileSdk 34

    def _versionCode = 0
    def _major = 0
    def _minor = 0
    def _patch = 0

    def versionPropsFile = file('version.properties')

    // Check if the build type is release
    if (gradle.startParameter.taskRequests.toString().contains("assembleRelease")) {
        if (versionPropsFile.canRead()) {
            def Properties versionProps = new Properties()

            versionProps.load(new FileInputStream(versionPropsFile))

            _patch = versionProps['PATCH'].toInteger() + 1
            _major = versionProps['MAJOR'].toInteger()
            _minor = versionProps['MINOR'].toInteger()
            _versionCode = versionProps['VERSION_CODE'].toInteger() + 1

            if (_patch == 20) {
                _patch = 0
                _minor = _minor + 1
            }
            if (_minor == 10) {
                _minor = 0
                _major = _major + 1
            }

            versionProps['MAJOR'] = _major.toString()
            versionProps['MINOR'] = _minor.toString()
            versionProps['PATCH'] = _patch.toString()
            versionProps['VERSION_CODE'] = _versionCode.toString()
            versionProps.store(versionPropsFile.newWriter(), null)
        } else {
            throw new GradleException("Could not read version.properties!")
        }
    } else if (versionPropsFile.canRead()) {
        def Properties versionProps = new Properties()

        versionProps.load(new FileInputStream(versionPropsFile))

        _patch = versionProps['PATCH'].toInteger()
        _major = versionProps['MAJOR'].toInteger()
        _minor = versionProps['MINOR'].toInteger()
        _versionCode = versionProps['VERSION_CODE'].toInteger()
    } else {
        throw new GradleException("Could not read version.properties!")
    }

    def _versionName = "${_major}.${_minor}.${_patch}(${_versionCode})"
    def _OnlyversionName = "${_major}.${_minor}.${_patch}"
    def _appVersionName = "${_major}.${_minor}.${_patch}-${_versionCode}"

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "android.iocl.dac_collector"
        minSdk 22
        targetSdk 33
        versionCode _versionCode
        versionName _appVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def name = "Aemm_V${_appVersionName}.apk"
            output.outputFileName = name
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}


dependencies {
    implementation(platform("com.google.firebase:firebase-bom:33.4.0"))
    implementation 'com.github.getActivity:XXPermissions:20.0'
    implementation "com.google.firebase:firebase-database"
    implementation("com.google.firebase:firebase-crashlytics")
    implementation("com.google.firebase:firebase-analytics")
    implementation("com.google.firebase:firebase-messaging")
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.0"
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'com.github.pwittchen:reactivenetwork-rx2:3.0.8'

    implementation 'com.google.android.gms:play-services-ads:23.3.0'
    implementation "com.google.android.material:material:1.3.0-alpha02"
    implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-gson:2.11.0")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation 'com.google.firebase:firebase-analytics'


    implementation 'com.google.android.material:material:1.9.0'
    implementation 'com.github.tiann:FreeReflection:3.1.0'







    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.core.ktx
    implementation libs.firebase.perf
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}


apply plugin: 'com.google.gms.google-services'